### ISSUE TITLE
How long will the Flash life issue take if I record history once every minute?

### ISSUE THREAD

**Issue by biencuong** [G6EJD/ESP32_Data_Logging_Webserver#1]
Hello, How long will the Flash life issue take if I record history once every minute?

**Comment by G6EJD** [comment]
Flash memory has a typical write-cycle life of 100,000 and statically you may get more.

100000/60/24=69 days. 

The flash has a write levelling function that tries to spread the locations for writing.

If the flash life extended to 1,000,000 then life would be (at 1-minute write intervals) 690 days.

This is not a code issue.
