### ISSUE TITLE
Calculate the total duration of operation from the log (attached image) and draw the timeline

### ISSUE THREAD

**Issue by biencuong** [G6EJD/ESP32_Data_Logging_Webserver#2]
Please help me,
Calculate the total duration of operation from the log (attached image 
![zalo_screenshot_22_2_2019_713503](https://user-images.githubusercontent.com/26410999/53225945-39974300-36ac-11e9-9822-91ea68fc5d6e.png)
) and draw the timeline

**Comment by G6EJD** [comment]
I do t recognise the log format is is from the IDE?
The web server has a streaming output of readings that if selected and copied can be pasted into Excel for graphing the time line without modification I organised the data output to match Excel or OpenOffice formats. 
What is the software error your reporting here?
