### ISSUE TITLE
autosmooth

### ISSUE THREAD

**Issue by Teletrabi** [G6EJD/ESP32_Data_Logging_Webserver#3]
Hi,
I am wondering about the purpose of ths line:
 if ((sensor_data[i+1].temp > (last_temp * 1.1)) || (sensor_data[i+1].temp < (last_temp * 1.1))) sensor_data[i+1].temp = (sensor_data[i+1].temp+last_temp)/2;

is " < (last_temp * 1.1)" correct? or should it be " < (last_temp / 1.1)"?

**Comment by G6EJD** [comment]
Yes, thank you that was an error, corrected now.
