### ISSUE TITLE
Google charts API updated

### ISSUE THREAD

**Issue by SimonMerrett** [G6EJD/ESP32_Data_Logging_Webserver#4]
Hi, thanks so much for your inspiring examples. I tried uploading this example to an ESP32 today and couldn't see the graphs. I tried following the helpful documentation in your comments and I may have traced it back to a new way that the google charts API works. This example worked on the same hardware around two or three months ago, so I think I can rule out other issues "at my end". I haven't yet (but plan to) implemented or tested the changes documented here but thought I'd bring it to your attention: https://developers.google.com/chart/interactive/docs/basic_load_libs#updateloader

**Comment by G6EJD** [comment]
Hello Simon, well about 2-months ago I updated the API calls to reflect the changes google made to their API and it was working, so now the question is, have they put things back again having realised or been informed it must have caused chaos!

**Comment by SimonMerrett** [comment]
I may have an out of date example - will check and close if so.

**Comment by SimonMerrett** [comment]
```
webpage += F("<script type=\"text/javascript\" src=\"https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}/\"></script>");
  webpage += F("<script type=\"text/javascript\">");
  webpage += F("google.charts.load('current', {packages: ['corechart', 'line']});");
  webpage += F("google.setOnLoadCallback(drawChart);");
  webpage += F("function drawChart() {");
  webpage += F("var data = google.visualization.arrayToDataTable([");
```
Is your current version (I did have an old version) and inserting these lines into my older version does mean that the graphing works - thank you.

It may be worth keeping an eye out (as I'm sure you are) because the new loader doesn't look like your code and the Google webpage says "Last updated 2020-07-08 UTC." so they might still be tinkering. Here's what their new method looks like:
```
<script src="https://www.gstatic.com/charts/loader.js"></script>
<script>
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawChart);
</script>
```

**Comment by G6EJD** [comment]
It was changed to the new method.

**Comment by SimonMerrett** [comment]
Thanks, not always clear which parts of their examples must be copied and which can be left as-is.
